Fix indentation.

diff --git a/.github/workflows/contract_validation_tests.yml b/.github/workflows/contract_validation_tests.yml
--- a/.github/workflows/contract_validation_tests.yml
+++ b/.github/workflows/contract_validation_tests.yml
@@ -40,21 +40,21 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Extract branch
-          id: extract-branch
-          run: |
-            GITHUB_EVENT_NAME=${{ github.event_name }}
-            if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
-              GITHUB_REF=${{ github.ref }}
-              GITHUB_SHA=${{ github.sha }}
-            elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
-              GITHUB_REF=refs/heads/${{ github.head_ref }}
-              GITHUB_SHA=${{ github.event.pull_request.head.sha }}
-            else
-              echo "Failed to extract branch information"
-              exit 1
-            fi
-            echo "ref=$GITHUB_REF" >> $GITHUB_OUTPUT
-            echo "sha=$GITHUB_SHA" >> $GITHUB_OUTPUT
+        id: extract-branch
+        run: |
+          GITHUB_EVENT_NAME=${{ github.event_name }}
+          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
+            GITHUB_REF=${{ github.ref }}
+            GITHUB_SHA=${{ github.sha }}
+          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
+            GITHUB_REF=refs/heads/${{ github.head_ref }}
+            GITHUB_SHA=${{ github.event.pull_request.head.sha }}
+          else
+            echo "Failed to extract branch information"
+            exit 1
+          fi
+          echo "ref=$GITHUB_REF" >> $GITHUB_OUTPUT
+          echo "sha=$GITHUB_SHA" >> $GITHUB_OUTPUT
 
       - name: list directories
         run: |
